export const brands = [
  "LIBERTY",
  "Biba",
  "Calvin Klein",
  "Fabindia",
  "Levi's",
  "Louis Philippe",
  "Monte Carlo",
  "Peter England",
  "Park Avenue",
  "Raymond",
  "LIBERTY",
  "Biba",
  "Calvin Klein",
  "Fabindia",
  "Levi's",
  "Louis Philippe",
  "Monte Carlo",
  "Peter England",
  "Park Avenue",
  "Raymond",
  "LIBERTY",
  "Biba",
  "Calvin Klein",
  "Fabindia",
  "Levi's",
  "Louis Philippe",
  "Monte Carlo",
  "Peter England",
  "Park Avenue",
  "Raymond",
  "LIBERTY",
  "Biba",
  "Calvin Klein",
  "Fabindia",
  "Levi's",
  "Louis Philippe",
  "Monte Carlo",
  "Peter England",
  "Park Avenue",
  "Raymond",
  "LIBERTY",
  "Biba",
  "Calvin Klein",
  "Fabindia",
  "Levi's",
  "Louis Philippe",
  "Monte Carlo",
  "Peter England",
  "Park Avenue",
  "Raymond",
  "LIBERTY",
  "Biba",
  "Calvin Klein",
  "Fabindia",
  "Levi's",
  "Louis Philippe",
  "Monte Carlo",
  "Peter England",
  "Park Avenue",
  "Raymond",
  "LIBERTY",
  "Biba",
  "Calvin Klein",
  "Fabindia",
  "Levi's",
  "Louis Philippe",
  "Monte Carlo",
  "Peter England",
  "Park Avenue",
  "Raymond",
  "LIBERTY",
  "Biba",
  "Calvin Klein",
  "Fabindia",
  "Levi's",
  "Louis Philippe",
  "Monte Carlo",
  "Peter England",
  "Park Avenue",
  "Raymond",
  "LIBERTY",
  "Biba",
  "Calvin Klein",
  "Fabindia",
  "Levi's",
  "Louis Philippe",
  "Monte Carlo",
  "Peter England",
  "Park Avenue",
  "Raymond",
  "LIBERTY",
  "Biba",
  "Calvin Klein",
  "Fabindia",
  "Levi's",
  "Louis Philippe",
  "Monte Carlo",
  "Peter England",
  "Park Avenue",
  "Raymond",
  "LIBERTY",
  "Biba",
  "Calvin Klein",
  "Fabindia",
  "Levi's",
  "Louis Philippe",
  "Monte Carlo",
  "Peter England",
  "Park Avenue",
  "Raymond",
  "LIBERTY",
  "Biba",
  "Calvin Klein",
  "Fabindia",
  "Levi's",
  "Louis Philippe",
  "Monte Carlo",
  "Peter England",
  "Park Avenue",
  "Raymond",
  "LIBERTY",
  "Biba",
  "Calvin Klein",
  "Fabindia",
  "Levi's",
  "Louis Philippe",
  "Monte Carlo",
  "Peter England",
  "Park Avenue",
  "Raymond",
  "LIBERTY",
  "Biba",
  "Calvin Klein",
  "Fabindia",
  "Levi's",
  "Louis Philippe",
  "Monte Carlo",
  "Peter England",
  "Park Avenue",
  "Raymond",
  "LIBERTY",
  "Biba",
  "Calvin Klein",
  "Fabindia",
  "Levi's",
  "Louis Philippe",
  "Monte Carlo",
  "Peter England",
  "Park Avenue",
  "Raymond",
];
